# Generated by Django 5.0 on 2023-12-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_tag_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['tags__name', 'serial_number']},
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
