# Generated by Django 5.0 on 2023-12-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_options_item_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['tags__name', 'uid']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.CharField(blank=True, help_text='Unique ID', max_length=100, null=True, unique=True, verbose_name='UID'),
        ),
    ]
