# Generated by Django 5.0 on 2023-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_computersystem_desktop_laptop_server_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersystem',
            name='type',
            field=models.CharField(choices=[('desktop', 'Desktop Computer'), ('laptop', 'Laptop Computer'), ('server', 'Server')], max_length=20, null=True),
        ),
    ]
