# Generated by Django 5.0 on 2023-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_computersystem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersystem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='computersystem',
            name='type',
            field=models.CharField(blank=True, choices=[('desktop', 'Desktop Computer'), ('laptop', 'Laptop Computer'), ('server', 'Server')], max_length=20, null=True),
        ),
    ]
