# Generated by Django 5.0 on 2023-12-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_computersystem_tags_alter_computersystem_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerSystem',
        ),
        migrations.DeleteModel(
            name='Desktop',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Tablet',
        ),
        migrations.AddField(
            model_name='item',
            name='hdd',
            field=models.IntegerField(default=100, help_text='HDD in GB'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='memory',
            field=models.IntegerField(default=8, help_text='RAM in GB'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
